# Generated by Django 5.2.8 on 2025-12-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_heater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='value',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
