# Generated by Django 5.2.8 on 2025-12-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_heater', '0004_alter_temperature_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='value',
            field=models.FloatField(),
        ),
    ]
